# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: MagicChunks@2
  inputs:
    sourcePath: 'gcp_auth.json'
    fileType: 'Json'
    targetPathType: 'source'
    transformationType: 'json'
    transformations: |
      {
        "project_id": "$(gcp_project_id)",
        "private_key_id": "$(gcp_private_key_id)",
        "private_key": "$(gcp_private_key)",
        "client_email": "$(gcp_client_email)",
        "client_id": "$(gcp_client_id)",
        "client_x509_cert_url": "$(gcp_client_x509_cert_url)"
      }

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      $String = @" 
      [gcp]
      type = google cloud storage
      project_number = $(gcp_project_number)
      service_account_file = ./gcp_auth.json
      bucket_policy_only = true
      "@
      $String >> rclone.conf
      cat rclone.conf

- task: Npm@1
  inputs:
    command: 'install'

- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    enableCodeCoverage: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
    ArtifactName: 'dist'
    publishLocation: 'Container'

